"""initial_schema

Revision ID: 24025de78a2d
Revises: 
Create Date: 2026-04-03 13:08:04.758214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '24025de78a2d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('testimonies',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('witness_id', sa.String(length=255), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'PROCESSED', 'FAILED', name='testimonystatus'), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_testimonies_status'), 'testimonies', ['status'], unique=False)
    op.create_index(op.f('ix_testimonies_witness_id'), 'testimonies', ['witness_id'], unique=False)
    op.create_table('timelines',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('testimony_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ordered_events', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('testimony_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('timestamp_hint', sa.String(length=255), nullable=True),
    sa.Column('resolved_timestamp', sa.String(length=64), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('participants', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='eventconfidence'), nullable=False),
    sa.Column('embedding_vector', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['testimony_id'], ['testimonies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_testimony_id'), 'events', ['testimony_id'], unique=False)
    op.create_table('questions',
    sa.Column('timeline_id', sa.UUID(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('target_event_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='questionpriority'), nullable=False),
    sa.Column('is_answered', sa.Boolean(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['timeline_id'], ['timelines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_timeline_id'), 'questions', ['timeline_id'], unique=False)
    op.create_table('conflicts',
    sa.Column('timeline_id', sa.UUID(), nullable=False),
    sa.Column('event_a_id', sa.UUID(), nullable=False),
    sa.Column('event_b_id', sa.UUID(), nullable=False),
    sa.Column('conflict_type', sa.Enum('TEMPORAL', 'FACTUAL', 'PARTICIPANT', 'LOCATION', 'CAUSAL', name='conflicttype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='conflictseverity'), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_a_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_b_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['timeline_id'], ['timelines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conflicts_timeline_id'), 'conflicts', ['timeline_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conflicts_timeline_id'), table_name='conflicts')
    op.drop_table('conflicts')
    op.drop_index(op.f('ix_questions_timeline_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_events_testimony_id'), table_name='events')
    op.drop_table('events')
    op.drop_table('timelines')
    op.drop_index(op.f('ix_testimonies_witness_id'), table_name='testimonies')
    op.drop_index(op.f('ix_testimonies_status'), table_name='testimonies')
    op.drop_table('testimonies')
    # ### end Alembic commands ###
