"""
ORM models: Timeline, Conflict, Question
"""

import uuid
from enum import Enum as PyEnum

from sqlalchemy import Enum, ForeignKey, String, Text
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base, TimestampMixin, UUIDPrimaryKeyMixin


# ---------------------------------------------------------------------------
# Timeline
# ---------------------------------------------------------------------------

class Timeline(Base, UUIDPrimaryKeyMixin, TimestampMixin):
    """
    A reconstructed chronological timeline built from multiple testimonies.
    """
    __tablename__ = "timelines"

    title: Mapped[str] = mapped_column(String(255), nullable=False)
    description: Mapped[str | None] = mapped_column(Text, nullable=True)
    testimony_ids: Mapped[list] = mapped_column(JSONB, nullable=False, default=list)
    ordered_events: Mapped[list] = mapped_column(JSONB, nullable=False, default=list)  # ordered list of event references
    meta: Mapped[dict] = mapped_column(JSONB, nullable=False, default=dict)

    conflicts: Mapped[list["Conflict"]] = relationship(
        "Conflict", back_populates="timeline", cascade="all, delete-orphan", lazy="selectin"
    )
    questions: Mapped[list["Question"]] = relationship(
        "Question", back_populates="timeline", cascade="all, delete-orphan", lazy="selectin"
    )


# ---------------------------------------------------------------------------
# Conflict
# ---------------------------------------------------------------------------

class ConflictSeverity(str, PyEnum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"


class ConflictType(str, PyEnum):
    TEMPORAL = "temporal"       # different timestamps for same event
    FACTUAL = "factual"         # contradictory facts
    PARTICIPANT = "participant" # different people named
    LOCATION = "location"       # different locations stated
    CAUSAL = "causal"           # disagreement on cause/effect


class Conflict(Base, UUIDPrimaryKeyMixin, TimestampMixin):
    """
    A detected contradiction between two events in different testimonies.
    """
    __tablename__ = "conflicts"

    timeline_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("timelines.id", ondelete="CASCADE"), nullable=False, index=True
    )
    event_a_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("events.id", ondelete="CASCADE"), nullable=False
    )
    event_b_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("events.id", ondelete="CASCADE"), nullable=False
    )
    conflict_type: Mapped[ConflictType] = mapped_column(Enum(ConflictType), nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=False)
    severity: Mapped[ConflictSeverity] = mapped_column(
        Enum(ConflictSeverity), nullable=False, default=ConflictSeverity.MEDIUM
    )
    is_resolved: Mapped[bool] = mapped_column(default=False)
    resolution_notes: Mapped[str | None] = mapped_column(Text, nullable=True)
    meta: Mapped[dict] = mapped_column(JSONB, nullable=False, default=dict)

    timeline: Mapped["Timeline"] = relationship("Timeline", back_populates="conflicts")
    event_a: Mapped["Event"] = relationship("Event", foreign_keys=[event_a_id], back_populates="conflicts_as_a")  # type: ignore[name-defined]
    event_b: Mapped["Event"] = relationship("Event", foreign_keys=[event_b_id], back_populates="conflicts_as_b")  # type: ignore[name-defined]


# ---------------------------------------------------------------------------
# Question
# ---------------------------------------------------------------------------

class QuestionPriority(str, PyEnum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"


class Question(Base, UUIDPrimaryKeyMixin, TimestampMixin):
    """
    A clarifying question generated by the AI to resolve gaps or conflicts.
    """
    __tablename__ = "questions"

    timeline_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("timelines.id", ondelete="CASCADE"), nullable=False, index=True
    )
    question_text: Mapped[str] = mapped_column(Text, nullable=False)
    target_event_ids: Mapped[list] = mapped_column(JSONB, nullable=False, default=list)
    priority: Mapped[QuestionPriority] = mapped_column(
        Enum(QuestionPriority), nullable=False, default=QuestionPriority.MEDIUM
    )
    is_answered: Mapped[bool] = mapped_column(default=False)
    answer: Mapped[str | None] = mapped_column(Text, nullable=True)
    meta: Mapped[dict] = mapped_column(JSONB, nullable=False, default=dict)

    timeline: Mapped["Timeline"] = relationship("Timeline", back_populates="questions")
